# Яндекс Музыка

Сравнение Москвы и Петербурга окружено мифами. Например:
 * Москва — мегаполис, подчинённый жёсткому ритму рабочей недели;
 * Петербург — культурная столица, со своими вкусами.

На данных Яндекс Музыки мы сравним поведение пользователей двух столиц.

**Цель исследования** — проверить три гипотезы:
1. Активность пользователей зависит от дня недели. Причём в Москве и Петербурге это проявляется по-разному.
2. В понедельник утром в Москве преобладают одни жанры, а в Петербурге — другие. Так же и вечером пятницы преобладают разные жанры — в зависимости от города.
3. Москва и Петербург предпочитают разные жанры музыки. В Москве чаще слушают поп-музыку, в Петербурге — русский рэп.

**Ход исследования**

Данные о поведении пользователей в файле `yandex_music_project.csv`. О качестве данных ничего не известно. Поэтому перед проверкой гипотез понадобится обзор данных.

Мы проверим данные на ошибки и оцените их влияние на исследование. Затем, на этапе предобработки поищем возможность исправить самые критичные ошибки данных.

Таким образом, исследование пройдёт в три этапа:
 1. Обзор данных.
 2. Предобработка данных.
 3. Проверка гипотез.

## Обзор данных

Составьте первое представление о данных Яндекс Музыки.

In [1]:
# импорт библиотеки pandas
import pandas as pd

In [2]:
# чтение файла с данными и сохранение в df
df = pd.read_csv('/datasets/yandex_music_project.csv')

In [3]:
# получение первых 10 строк таблицы df
df.head(10)

,userID,Track,artist,genre,City,time,Day
0,FFB692EC,Kamigata To Boots,The Mass Missile,rock,Saint-Petersburg,20:28:33,Wednesday
1,55204538,Delayed Because of Accident,Andreas Rönnberg,rock,Moscow,14:07:09,Friday
2,20EC38,Funiculì funiculà,Mario Lanza,pop,Saint-Petersburg,20:58:07,Wednesday
3,A3DD03C9,Dragons in the Sunset,Fire + Ice,folk,Saint-Petersburg,08:37:09,Monday
4,E2DC1FAE,Soul People,Space Echo,dance,Moscow,08:34:34,Monday
5,842029A1,Преданная,IMPERVTOR,rusrap,Saint-Petersburg,13:09:41,Friday
6,4CB90AA5,True,Roman Messer,dance,Moscow,13:00:07,Wednesday
7,F03E1C1F,Feeling This Way,Polina Griffith,dance,Moscow,20:47:49,Wednesday
8,8FA1D3BE,И вновь продолжается бой,NaN,ruspop,Moscow,09:17:40,Friday
9,E772D5C0,Pessimist,NaN,dance,Saint-Petersburg,21:20:49,Wednesday

In [4]:
# получение общей информации о данных в таблице df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65079 entries, 0 to 65078
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0     userID  65079 non-null  object
 1   Track     63848 non-null  object
 2   artist    57876 non-null  object
 3   genre     63881 non-null  object
 4     City    65079 non-null  object
 5   time      65079 non-null  object
 6   Day       65079 non-null  object
dtypes: object(7)
memory usage: 3.5+ MB

Количество значений в столбцах различается. Значит, в данных есть пропущенные значения.

In [5]:
# Напишите ваш ответ здесь комментарием. Не удаляйте символ #. Не меняйте тип этой ячейки на Markdown.
# Столбец userID можно записать как user_id (змеиный регистр)

**Выводы**

В каждой строке таблицы — данные о прослушанном треке. Часть колонок описывает саму композицию: название, исполнителя и жанр. Остальные данные рассказывают о пользователе: из какого он города, когда он слушал музыку.

Предварительно можно утверждать, что данных достаточно для проверки гипотез. Но встречаются пропуски в данных, а в названиях колонок — расхождения с хорошим стилем.

Чтобы двигаться дальше, нужно устранить проблемы в данных.

## Предобработка данных

### Переименование столбцов

In [6]:
# перечень названий столбцов таблицы df
df.columns

Index(['  userID', 'Track', 'artist', 'genre', '  City  ', 'time', 'Day'], dtype='object')

In [7]:
# переименование столбцов
df = df.rename(
    columns = {
        '  userID': 'user_id',
        'Track': 'track',
        '  City  ': 'city',
        'Day': 'day',
    }

)

In [8]:
# проверка результатов - перечень названий столбцов
df.columns

Index(['user_id', 'track', 'artist', 'genre', 'city', 'time', 'day'], dtype='object')

### Обработка пропущенных значений

In [9]:
# подсчёт пропусков
df.isna().sum()

user_id       0
track      1231
artist     7203
genre      1198
city          0
time          0
day           0
dtype: int64

In [10]:
# замена пропущенных значений на 'unknown'
df = df.fillna('unknown')

In [11]:
# проверка на отсутствие пропусков
df.isna().sum()

user_id    0
track      0
artist     0
genre      0
city       0
time       0
day        0
dtype: int64

### Обработка дубликатов

In [12]:
# подсчёт явных дубликатов
df.duplicated().sum()

3826

In [13]:
# удаление явных дубликатов, создание новых индексов и удаление старых
df = df.drop_duplicates().reset_index(drop=True)

In [14]:
# проверка на отсутствие явных дубликатов
df.duplicated().sum()

0

In [15]:
# просмотр уникальных отсортированных названий жанров
df['genre'].sort_values().unique()
sorted(df['genre'].unique())

['acid',
 'acoustic',
 'action',
 'adult',
 'africa',
 'afrikaans',
 'alternative',
 'alternativepunk',
 'ambient',
 'americana',
 'animated',
 'anime',
 'arabesk',
 'arabic',
 'arena',
 'argentinetango',
 'art',
 'audiobook',
 'author',
 'avantgarde',
 'axé',
 'baile',
 'balkan',
 'beats',
 'bigroom',
 'black',
 'bluegrass',
 'blues',
 'bollywood',
 'bossa',
 'brazilian',
 'breakbeat',
 'breaks',
 'broadway',
 'cantautori',
 'cantopop',
 'canzone',
 'caribbean',
 'caucasian',
 'celtic',
 'chamber',
 'chanson',
 'children',
 'chill',
 'chinese',
 'choral',
 'christian',
 'christmas',
 'classical',
 'classicmetal',
 'club',
 'colombian',
 'comedy',
 'conjazz',
 'contemporary',
 'country',
 'cuban',
 'dance',
 'dancehall',
 'dancepop',
 'dark',
 'death',
 'deep',
 'deutschrock',
 'deutschspr',
 'dirty',
 'disco',
 'dnb',
 'documentary',
 'downbeat',
 'downtempo',
 'drum',
 'dub',
 'dubstep',
 'eastern',
 'easy',
 'electronic',
 'electropop',
 'emo',
 'entehno',
 'epicmetal',
 'estrada',
 'ethnic',
 'eurofolk',
 'european',
 'experimental',
 'extrememetal',
 'fado',
 'fairytail',
 'film',
 'fitness',
 'flamenco',
 'folk',
 'folklore',
 'folkmetal',
 'folkrock',
 'folktronica',
 'forró',
 'frankreich',
 'französisch',
 'french',
 'funk',
 'future',
 'gangsta',
 'garage',
 'german',
 'ghazal',
 'gitarre',
 'glitch',
 'gospel',
 'gothic',
 'grime',
 'grunge',
 'gypsy',
 'handsup',
 "hard'n'heavy",
 'hardcore',
 'hardstyle',
 'hardtechno',
 'hip',
 'hip-hop',
 'hiphop',
 'historisch',
 'holiday',
 'hop',
 'horror',
 'house',
 'hymn',
 'idm',
 'independent',
 'indian',
 'indie',
 'indipop',
 'industrial',
 'inspirational',
 'instrumental',
 'international',
 'irish',
 'jam',
 'japanese',
 'jazz',
 'jewish',
 'jpop',
 'jungle',
 'k-pop',
 'karadeniz',
 'karaoke',
 'kayokyoku',
 'korean',
 'laiko',
 'latin',
 'latino',
 'leftfield',
 'local',
 'lounge',
 'loungeelectronic',
 'lovers',
 'malaysian',
 'mandopop',
 'marschmusik',
 'meditative',
 'mediterranean',
 'melodic',
 'metal',
 'metalcore',
 'mexican',
 'middle',
 'minimal',
 'miscellaneous',
 'modern',
 'mood',
 'mpb',
 'muslim',
 'native',
 'neoklassik',
 'neue',
 'new',
 'newage',
 'newwave',
 'nu',
 'nujazz',
 'numetal',
 'oceania',
 'old',
 'opera',
 'orchestral',
 'other',
 'piano',
 'podcasts',
 'pop',
 'popdance',
 'popelectronic',
 'popeurodance',
 'poprussian',
 'post',
 'posthardcore',
 'postrock',
 'power',
 'progmetal',
 'progressive',
 'psychedelic',
 'punjabi',
 'punk',
 'quebecois',
 'ragga',
 'ram',
 'rancheras',
 'rap',
 'rave',
 'reggae',
 'reggaeton',
 'regional',
 'relax',
 'religious',
 'retro',
 'rhythm',
 'rnb',
 'rnr',
 'rock',
 'rockabilly',
 'rockalternative',
 'rockindie',
 'rockother',
 'romance',
 'roots',
 'ruspop',
 'rusrap',
 'rusrock',
 'russian',
 'salsa',
 'samba',
 'scenic',
 'schlager',
 'self',
 'sertanejo',
 'shanson',
 'shoegazing',
 'showtunes',
 'singer',
 'ska',
 'skarock',
 'slow',
 'smooth',
 'soft',
 'soul',
 'soulful',
 'sound',
 'soundtrack',
 'southern',
 'specialty',
 'speech',
 'spiritual',
 'sport',
 'stonerrock',
 'surf',
 'swing',
 'synthpop',
 'synthrock',
 'sängerportrait',
 'tango',
 'tanzorchester',
 'taraftar',
 'tatar',
 'tech',
 'techno',
 'teen',
 'thrash',
 'top',
 'traditional',
 'tradjazz',
 'trance',
 'tribal',
 'trip',
 'triphop',
 'tropical',
 'türk',
 'türkçe',
 'ukrrock',
 'unknown',
 'urban',
 'uzbek',
 'variété',
 'vi',
 'videogame',
 'vocal',
 'western',
 'world',
 'worldbeat',
 'ïîï',
 'электроника']

In [16]:
# просмотр уникальных названий жанров
df['genre'].unique()
# устранение неявных дубликатов
df = df.replace(['hip', 'hop', 'hip-hop'], 'hiphop')

In [17]:
# проверка на отсутствие неявных дубликатов
# просмотр уникальных отсортированных названий жанров
df['genre'].sort_values().unique()
sorted(df['genre'].unique())

['acid',
 'acoustic',
 'action',
 'adult',
 'africa',
 'afrikaans',
 'alternative',
 'alternativepunk',
 'ambient',
 'americana',
 'animated',
 'anime',
 'arabesk',
 'arabic',
 'arena',
 'argentinetango',
 'art',
 'audiobook',
 'author',
 'avantgarde',
 'axé',
 'baile',
 'balkan',
 'beats',
 'bigroom',
 'black',
 'bluegrass',
 'blues',
 'bollywood',
 'bossa',
 'brazilian',
 'breakbeat',
 'breaks',
 'broadway',
 'cantautori',
 'cantopop',
 'canzone',
 'caribbean',
 'caucasian',
 'celtic',
 'chamber',
 'chanson',
 'children',
 'chill',
 'chinese',
 'choral',
 'christian',
 'christmas',
 'classical',
 'classicmetal',
 'club',
 'colombian',
 'comedy',
 'conjazz',
 'contemporary',
 'country',
 'cuban',
 'dance',
 'dancehall',
 'dancepop',
 'dark',
 'death',
 'deep',
 'deutschrock',
 'deutschspr',
 'dirty',
 'disco',
 'dnb',
 'documentary',
 'downbeat',
 'downtempo',
 'drum',
 'dub',
 'dubstep',
 'eastern',
 'easy',
 'electronic',
 'electropop',
 'emo',
 'entehno',
 'epicmetal',
 'estrada',
 'ethnic',
 'eurofolk',
 'european',
 'experimental',
 'extrememetal',
 'fado',
 'fairytail',
 'film',
 'fitness',
 'flamenco',
 'folk',
 'folklore',
 'folkmetal',
 'folkrock',
 'folktronica',
 'forró',
 'frankreich',
 'französisch',
 'french',
 'funk',
 'future',
 'gangsta',
 'garage',
 'german',
 'ghazal',
 'gitarre',
 'glitch',
 'gospel',
 'gothic',
 'grime',
 'grunge',
 'gypsy',
 'handsup',
 "hard'n'heavy",
 'hardcore',
 'hardstyle',
 'hardtechno',
 'hiphop',
 'historisch',
 'holiday',
 'horror',
 'house',
 'hymn',
 'idm',
 'independent',
 'indian',
 'indie',
 'indipop',
 'industrial',
 'inspirational',
 'instrumental',
 'international',
 'irish',
 'jam',
 'japanese',
 'jazz',
 'jewish',
 'jpop',
 'jungle',
 'k-pop',
 'karadeniz',
 'karaoke',
 'kayokyoku',
 'korean',
 'laiko',
 'latin',
 'latino',
 'leftfield',
 'local',
 'lounge',
 'loungeelectronic',
 'lovers',
 'malaysian',
 'mandopop',
 'marschmusik',
 'meditative',
 'mediterranean',
 'melodic',
 'metal',
 'metalcore',
 'mexican',
 'middle',
 'minimal',
 'miscellaneous',
 'modern',
 'mood',
 'mpb',
 'muslim',
 'native',
 'neoklassik',
 'neue',
 'new',
 'newage',
 'newwave',
 'nu',
 'nujazz',
 'numetal',
 'oceania',
 'old',
 'opera',
 'orchestral',
 'other',
 'piano',
 'podcasts',
 'pop',
 'popdance',
 'popelectronic',
 'popeurodance',
 'poprussian',
 'post',
 'posthardcore',
 'postrock',
 'power',
 'progmetal',
 'progressive',
 'psychedelic',
 'punjabi',
 'punk',
 'quebecois',
 'ragga',
 'ram',
 'rancheras',
 'rap',
 'rave',
 'reggae',
 'reggaeton',
 'regional',
 'relax',
 'religious',
 'retro',
 'rhythm',
 'rnb',
 'rnr',
 'rock',
 'rockabilly',
 'rockalternative',
 'rockindie',
 'rockother',
 'romance',
 'roots',
 'ruspop',
 'rusrap',
 'rusrock',
 'russian',
 'salsa',
 'samba',
 'scenic',
 'schlager',
 'self',
 'sertanejo',
 'shanson',
 'shoegazing',
 'showtunes',
 'singer',
 'ska',
 'skarock',
 'slow',
 'smooth',
 'soft',
 'soul',
 'soulful',
 'sound',
 'soundtrack',
 'southern',
 'specialty',
 'speech',
 'spiritual',
 'sport',
 'stonerrock',
 'surf',
 'swing',
 'synthpop',
 'synthrock',
 'sängerportrait',
 'tango',
 'tanzorchester',
 'taraftar',
 'tatar',
 'tech',
 'techno',
 'teen',
 'thrash',
 'top',
 'traditional',
 'tradjazz',
 'trance',
 'tribal',
 'trip',
 'triphop',
 'tropical',
 'türk',
 'türkçe',
 'ukrrock',
 'unknown',
 'urban',
 'uzbek',
 'variété',
 'vi',
 'videogame',
 'vocal',
 'western',
 'world',
 'worldbeat',
 'ïîï',
 'электроника']

**Выводы**

Предобработка обнаружила три проблемы в данных:

- нарушения в стиле заголовков,
- пропущенные значения,
- дубликаты — явные и неявные.

Вы исправили заголовки, чтобы упростить работу с таблицей. Без дубликатов исследование станет более точным.

Пропущенные значения вы заменили на `'unknown'`. Ещё предстоит увидеть, не повредят ли исследованию пропуски в колонке `genre`.

Теперь можно перейти к проверке гипотез.

## Проверка гипотез

### Сравнение поведения пользователей двух столиц

Первая гипотеза утверждает, что пользователи по-разному слушают музыку в Москве и Санкт-Петербурге. Проверим это предположение по данным о трёх днях недели — понедельнике, среде и пятнице. Для этого:

* Разделим пользователей Москвы и Санкт-Петербурга.
* Сравним, сколько треков послушала каждая группа пользователей в понедельник, среду и пятницу.

In [20]:
# подсчёт прослушиваний в каждом городе
df.groupby('city')['time'].count()

city
Moscow              42741
Saint-Petersburg    18512
Name: time, dtype: int64

In [21]:
# подсчёт прослушиваний в каждый из трёх дней
df.groupby('day')['time'].count()

day
Friday       21840
Monday       21354
Wednesday    18059
Name: time, dtype: int64

In [27]:
def number_tracks(day, city):
    track_list = df[df['day'] == day]# выберите только строки df со значением переменной day в столбце day
    track_list = track_list[track_list['city'] == city]# выберите только строки track_list со значением переменной city в столбце city
    track_list_count = track_list.count()['user_id']# вызовите метод подсчета строк для track_list и выберите столбец user_id
    return track_list_count# верните значение track_list_count из функции

In [29]:
# количество прослушиваний в Москве по понедельникам
print(number_tracks('Monday', 'Moscow'))

15740

In [30]:
# количество прослушиваний в Санкт-Петербурге по понедельникам
print(number_tracks('Monday', 'Saint-Petersburg'))

5614

In [31]:
# количество прослушиваний в Москве по средам
print(number_tracks('Wednesday', 'Moscow'))

11056

In [32]:
# количество прослушиваний в Санкт-Петербурге по средам
print(number_tracks('Wednesday', 'Saint-Petersburg'))

7003

In [33]:
# количество прослушиваний в Москве по пятницам
print(number_tracks('Friday', 'Moscow'))

15945

In [34]:
# количество прослушиваний в Санкт-Петербурге по пятницам
print(number_tracks('Friday', 'Saint-Petersburg'))

5895

In [39]:
# создание таблицы с результатами
# вывод таблицы на экран
res = pd.DataFrame(data=[['Moscow',15740,11056,15945], ['Saint-Petersburg',5614,7003,5895]], columns=['city', 'monday','wednesday','friday'])
print(res)

               city  monday  wednesday  friday
0            Moscow   15740      11056   15945
1  Saint-Petersburg    5614       7003    5895

**Выводы**

Данные показывают разницу поведения пользователей:

- В Москве пик прослушиваний приходится на понедельник и пятницу, а в среду заметен спад.
- В Петербурге, наоборот, больше слушают музыку по средам. Активность в понедельник и пятницу здесь почти в равной мере уступает среде.

Значит, данные говорят в пользу первой гипотезы.

### Музыка в начале и в конце недели

Согласно второй гипотезе, утром в понедельник в Москве преобладают одни жанры, а в Петербурге — другие. Так же и вечером пятницы преобладают разные жанры — в зависимости от города.

In [46]:
# получение таблицы moscow_general из тех строк таблицы df, для которых значение в столбце 'city' равно 'Moscow'
moscow_general = df[df['city'] == 'Moscow']
moscow_general

,user_id,track,artist,genre,city,time,day
1,55204538,Delayed Because of Accident,Andreas Rönnberg,rock,Moscow,14:07:09,Friday
4,E2DC1FAE,Soul People,Space Echo,dance,Moscow,08:34:34,Monday
6,4CB90AA5,True,Roman Messer,dance,Moscow,13:00:07,Wednesday
7,F03E1C1F,Feeling This Way,Polina Griffith,dance,Moscow,20:47:49,Wednesday
8,8FA1D3BE,И вновь продолжается бой,unknown,ruspop,Moscow,09:17:40,Friday
...,...,...,...,...,...,...,...
61247,83A474E7,I Worship Only What You Bleed,The Black Dahlia Murder,extrememetal,Moscow,21:07:12,Monday
61248,729CBB09,My Name,McLean,rnb,Moscow,13:32:28,Wednesday
61250,C5E3A0D5,Jalopiina,unknown,industrial,Moscow,20:09:26,Friday
61251,321D0506,Freight Train,Chas McDevitt,rock,Moscow,21:43:59,Friday
61252,3A64EF84,Tell Me Sweet Little Lies,Monica Lopez,country,Moscow,21:59:46,Friday

In [47]:
# получение таблицы spb_general из тех строк таблицы df, для которых значение в столбце 'city' равно 'Saint-Petersburg'
spb_general = df[df['city'] == 'Saint-Petersburg']
spb_general

,user_id,track,artist,genre,city,time,day
0,FFB692EC,Kamigata To Boots,The Mass Missile,rock,Saint-Petersburg,20:28:33,Wednesday
2,20EC38,Funiculì funiculà,Mario Lanza,pop,Saint-Petersburg,20:58:07,Wednesday
3,A3DD03C9,Dragons in the Sunset,Fire + Ice,folk,Saint-Petersburg,08:37:09,Monday
5,842029A1,Преданная,IMPERVTOR,rusrap,Saint-Petersburg,13:09:41,Friday
9,E772D5C0,Pessimist,unknown,dance,Saint-Petersburg,21:20:49,Wednesday
...,...,...,...,...,...,...,...
61239,D94F810B,Theme from the Walking Dead,Proyecto Halloween,film,Saint-Petersburg,21:14:40,Monday
61240,BC8EC5CF,Red Lips: Gta (Rover Rework),Rover,electronic,Saint-Petersburg,21:06:50,Monday
61241,29E04611,Bre Petrunko,Perunika Trio,world,Saint-Petersburg,13:56:00,Monday
61242,1B91C621,(Hello) Cloud Mountain,sleepmakeswaves,postrock,Saint-Petersburg,09:22:13,Monday
61249,D08D4A55,Maybe One Day (feat. Black Spade),Blu & Exile,hiphop,Saint-Petersburg,10:00:00,Monday

In [59]:
def genre_weekday(df, day, time1, time2):
    # последовательная фильтрация
    # оставляем в genre_df только те строки df, у которых день равен day
    genre_df = df[df['day'] == day]# ваш код здесь
    # оставляем в genre_df только те строки genre_df, у которых время меньше time2
    genre_df = genre_df[genre_df['time'] < time2]# ваш код здесь
    # оставляем в genre_df только те строки genre_df, у которых время больше time1
    genre_df = genre_df[genre_df['time'] > time1]# ваш код здесь
    # сгруппируем отфильтрованный датафрейм по столбцу с названиями жанров, возьмём столбец genre и посчитаем кол-во строк для каждого жанра методом count()
    genre_df_grouped = genre_df.groupby('genre')['genre'].count()# ваш код здесь
    # отсортируем результат по убыванию (чтобы в начале Series оказались самые популярные жанры)
    genre_df_sorted = genre_df_grouped.sort_values(ascending=False)# ваш код здесь
    # вернём Series с 10 самыми популярными жанрами в указанный отрезок времени заданного дня
    return genre_df_sorted[:10]

In [60]:
# вызов функции для утра понедельника в Москве (вместо df — таблица moscow_general)
print(genre_weekday(moscow_general, 'Monday', '07:00', '11:00'))

genre
pop            781
dance          549
electronic     480
rock           474
hiphop         286
ruspop         186
world          181
rusrap         175
alternative    164
unknown        161
Name: genre, dtype: int64

In [61]:
# вызов функции для утра понедельника в Петербурге (вместо df — таблица spb_general)
print(genre_weekday(spb_general, 'Monday', '07:00', '11:00'))

genre
pop            218
dance          182
rock           162
electronic     147
hiphop          80
ruspop          64
alternative     58
rusrap          55
jazz            44
classical       40
Name: genre, dtype: int64

In [64]:
# вызов функции для вечера пятницы в Москве
print(genre_weekday(moscow_general, 'Friday', '17:00', '23:00'))

genre
pop            713
rock           517
dance          495
electronic     482
hiphop         273
world          208
ruspop         170
alternative    163
classical      163
rusrap         142
Name: genre, dtype: int64

In [65]:
# вызов функции для вечера пятницы в Петербурге
print(genre_weekday(spb_general, 'Friday', '17:00', '23:00'))

genre
pop            256
electronic     216
rock           216
dance          210
hiphop          97
alternative     63
jazz            61
classical       60
rusrap          59
world           54
Name: genre, dtype: int64

**Выводы**

Если сравнить топ-10 жанров в понедельник утром, можно сделать такие выводы:

1. В Москве и Петербурге слушают похожую музыку. Единственное различие — в московский рейтинг вошёл жанр “world”, а в петербургский — джаз и классика.

2. В Москве пропущенных значений оказалось так много, что значение `'unknown'` заняло десятое место среди самых популярных жанров. Значит, пропущенные значения занимают существенную долю в данных и угрожают достоверности исследования.

Вечер пятницы не меняет эту картину. Некоторые жанры поднимаются немного выше, другие спускаются, но в целом топ-10 остаётся тем же самым.

Таким образом, вторая гипотеза подтвердилась лишь частично:
* Пользователи слушают похожую музыку в начале недели и в конце.
* Разница между Москвой и Петербургом не слишком выражена. В Москве чаще слушают русскую популярную музыку, в Петербурге — джаз.

Однако пропуски в данных ставят под сомнение этот результат. В Москве их так много, что рейтинг топ-10 мог бы выглядеть иначе, если бы не утерянные  данные о жанрах.

### Жанровые предпочтения в Москве и Петербурге

Гипотеза: Петербург — столица рэпа, музыку этого жанра там слушают чаще, чем в Москве.  А Москва — город контрастов, в котором, тем не менее, преобладает поп-музыка.

In [74]:
# одной строкой: группировка таблицы moscow_general по столбцу 'genre', выбор столбца `genre`, подсчёт числа значений 'genre' методом count(), сохранение в moscow_genres
# сортировка получившегося Series в порядке убывания и сохранение обратно в moscow_genres
moscow_genres = moscow_general.groupby('genre')['genre'].count()
moscow_genres = moscow_genres.sort_values(ascending = False)

In [69]:
# просмотр первых 10 строк moscow_genres
moscow_genres.head(10)

genre
pop            5892
dance          4435
rock           3965
electronic     3786
hiphop         2096
classical      1616
world          1432
alternative    1379
ruspop         1372
rusrap         1161
Name: genre, dtype: int64

In [75]:
# одной строкой: группировка таблицы spb_general по столбцу 'genre', выбор столбца `genre`, подсчёт числа значений 'genre' методом count(), сохранение в spb_genres
# сортировка получившегося Series в порядке убывания и сохранение обратно в spb_genres
spb_genres = spb_general.groupby('genre')['genre'].count()
spb_genres = spb_genres.sort_values(ascending = False)

In [73]:
# просмотр первых 10 строк spb_genres
spb_genres.head(10)

genre
pop            2431
dance          1932
rock           1879
electronic     1736
hiphop          960
alternative     649
classical       646
rusrap          564
ruspop          538
world           515
Name: genre, dtype: int64

**Выводы**

Гипотеза частично подтвердилась:
* Поп-музыка — самый популярный жанр в Москве, как и предполагала гипотеза. Более того, в топ-10 жанров встречается близкий жанр — русская популярная музыка.
* Вопреки ожиданиям, рэп одинаково популярен в Москве и Петербурге.

## Итоги исследования

Вы проверили три гипотезы и установили:

1. День недели по-разному влияет на активность пользователей в Москве и Петербурге.

Первая гипотеза полностью подтвердилась.

2. Музыкальные предпочтения не сильно меняются в течение недели — будь то Москва или Петербург. Небольшие различия заметны в начале недели, по понедельникам:
* в Москве слушают музыку жанра “world”,
* в Петербурге — джаз и классику.

Таким образом, вторая гипотеза подтвердилась лишь отчасти. Этот результат мог оказаться иным, если бы не пропуски в данных.

3. Во вкусах пользователей Москвы и Петербурга больше общего, чем различий. Вопреки ожиданиям, предпочтения жанров в Петербурге напоминают московские.

Третья гипотеза не подтвердилась. Если различия в предпочтениях и существуют, на основной массе пользователей они незаметны.

**На практике исследования содержат проверки статистических гипотез.**
Из части данных одного сервиса невозможно сделать какие-то выводы о всех пользователях сервиса без методов статистики.
Проверки статистических гипотез покажут, насколько они достоверны, исходя из имеющихся данных.
С методами проверок гипотез вы ещё познакомитесь в следующих темах.